# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d07ea377b391a7ae147bfb4c28acdf4b937186dce58e4ff1be548331e33e2a6dfb9ae749253ef740481113b69eb918eae050f755fe2603b54d81b21d26a0187

test:
  secret_key_base: d695bb55c409be0137ceca39e0b17b9a7befa8a4ef48da5f7ea42379410abe57893cf72f7bd408a7ee84cc324ee2182e22436150c5dc86a1fb217fe158b03069

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
